# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
cn_PnPoly <- function(P, V) {
    .Call('_pfft_cn_PnPoly', PACKAGE = 'pfft', P, V)
}

#' @export
wn_PnPoly <- function(P, V) {
    .Call('_pfft_wn_PnPoly', PACKAGE = 'pfft', P, V)
}

#' @export
#' @Reference \url{http://geomalgorithms.com/a03-_inclusion.html}
#' @return The point is outside/on board only when this "winding number" wn = 0; otherwise, the point is inside.
PnPoly <- function(P, V) {
    .Call('_pfft_PnPoly', PACKAGE = 'pfft', P, V)
}

